#include "2d.h"
#include "bezierstuff.h"
#include "misc.h"
#include "primitives.h"
#include "shaders.h"
#include "tcl_pmap.h"
#include "ttf.h"

#include <stdio.h>
#include <stdlib.h>
#include <strings.h>
#include <string.h>
#include <math.h>
#include <signal.h>
#include <tcl.h>
#include <tclstuff.h>
#include <sys/time.h>
#include <unistd.h>
#include <wchar.h>
#include <locale.h>
