#include <Pixel/2d.h>
#include <Pixel/bezierstuff.h>
#include <Pixel/misc.h>
#include <Pixel/primitives.h>
#include <Pixel/shaders.h>
#include <Pixel/tcl_pmap.h>
#include <Pixel/tcl_utils.h>
#include <Pixel/rle.h>

#include <stdio.h>
#include <stdlib.h>
#include <strings.h>
#include <string.h>
#include <math.h>
#include <signal.h>
#include <tcl.h>
#include <tclstuff.h>
#include <sys/time.h>
#include <unistd.h>
#include <wchar.h>
#include <locale.h>
